CREATE DATABASE IF NOT EXISTS commerce;

USE commerce;


CREATE TABLE IF NOT EXISTS category (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `order` (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  num_invoice VARCHAR(100) NOT NULL,
  status      VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  num_user    BIGINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS productOrder (
  PRIMARY KEY (num_product, num_order),
  quantite    INT UNSIGNED(100),
);

CREATE TABLE IF NOT EXISTS productTag (
  PRIMARY KEY (num_tag, num_product)
);

CREATE TABLE IF NOT EXISTS product (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name         VARCHAR(100) NOT NULL,
  quantity     INT UNSIGNED(100),
  status       INT UNSIGNED(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  num_category BIGINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS tag (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name       VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name       VARCHAR(100) NOT NULL,
  password       VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE order ADD FOREIGN KEY (user_id) REFERENCES user (id);

ALTER TABLE productOrder ADD FOREIGN KEY (order_id) REFERENCES `order` (id);
ALTER TABLE productOrder ADD FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE productTag ADD FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE SET NULL;
ALTER TABLE productTag ADD FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE SET NULL;

ALTER TABLE Product ADD FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL;
